### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kacperleague9** [Jakubson/JPremiumCleared#10]
I dont get join from proxy message on my hub
https://i.imgur.com/MqjtVx6.png

**Comment by Jakubson** [comment]
Hi, I give support only on SpigotMC, please contact with me on SpigotMC and I will help you with all issues: https://www.spigotmc.org/conversations/add?to=Jakubson
If you cannot open a conversation, please leave a message on my profile page that you want to contact with me: https://www.spigotmc.org/members/jakubson.207724/
