### ISSUE TITLE
Error: preLoginErrorAntiBot

### ISSUE THREAD

**Issue by OllieBittern** [Jakubson/JPremiumCleared#13]
Hello,
Can I please have some help with this error? I use a bungeecord network.
![image](https://user-images.githubusercontent.com/80921589/117165215-35ebc480-adbd-11eb-806f-df394aeb9fca.png)

**Comment by Jakubson** [comment]
Hello! I give support only on SpigotMC in private messages. So, please contact with me there: https://www.spigotmc.org/conversations/add?to=Jakubson Then I will help you with your issue.

**Comment by OllieBittern** [comment]
I did try to.
![image](https://user-images.githubusercontent.com/80921589/117346711-05c92200-aea0-11eb-8ba7-027ac0dd6ced.png)

**Comment by Jakubson** [comment]
SpigotMC does not allow to send private messages when your account is too young.
So, please write me your SpigotMC nickname here (and I will open a conversation) or send me a message on my SpigotMC profile page.
