### ISSUE TITLE
Webmail password variable not working

### ISSUE THREAD

**Issue by KnightLegionNetwork** [Jakubson/JPremiumCleared#15]
Hello, I'm here to report that the %password% variable in the recovery.html isn't working.
When I send the mail all is working, the IP and the nickname are working, but the password no so it shows just %password%

**Comment by Jakubson** [comment]
Hello! I give support only on SpigotMC, so please contact with on there: https://www.spigotmc.org/conversations/add?to=Jakubson
If you cannot open a conversation, please just send me your SpigotMC nickname and I will open it.
