### ISSUE TITLE
Cracked players can`t join to the server with premium nicknames. 

### ISSUE THREAD

**Issue by HyenaBlyat** [Jakubson/JPremiumCleared#17]
I tried all the UUIDs, but not with one of them cracked players cannot connect to the server with premium nicknames.

**Comment by Jakubson** [comment]
Hello! I give support only on SpigotMC, so please contact with on there: https://www.spigotmc.org/conversations/add?to=Jakubson
If you cannot open a conversation, please just send me your SpigotMC nickname and I will open it.
