### ISSUE TITLE
FIXED UUIDs

### ISSUE THREAD

**Issue by TadiklCZE** [Jakubson/JPremiumCleared#2]
Hello, there is an issue with using FIXED UUIDs.

I was using luckperms and I got info about that luckperms is saving only type 3 UUID if the server is in offline mode. So data got corrupted and I couldn't join to my server.

Here is an error of trying to join the server:
https://hastebin.com/xexotunobu.yaml

Also I was trying to PM you on Discord, but you didn't even accept my request. And I can't message you on spigotmc.

**Comment by Jakubson** [comment]
Hi, I do not often visit issues on Github. I am sorry that I reply so late. We have already a started conversation on SpigotMC: https://www.spigotmc.org/conversations/jpremium.415090/
Please write in that conversation and I will help you with all issues.
