### ISSUE TITLE
Dupe inventory

### ISSUE THREAD

**Issue by PABLORAGNIzc** [Jakubson/JPremiumCleared#24]
Good. There is a way to duplicate items with the inventory by changing the nickname of the premium account.

When changing nick (a premium account) and if you have activated / premium.
When you re-enter with the old nick, it lets you register and duplicates what you had in the inventory
You appear in the new nick with the things and in the old

How can I disable this from happening?

**Comment by PABLORAGNIzc** [comment]
What happens if in uniqueIdsType I put FIXED already having registered users? This option is causing a lot of problems to my server and weird bugs.

**Comment by Jakubson** [comment]
What exactly unique UUIDs type you have in your JPremium configuration now?
Does the player who joined after a nickname change using the old nickname have a new UUID?
Does the premium player who change a nickname keep all data (like inventory, ranks, etc.)?


> What happens if in uniqueIdsType I put OFFLINE already having registered users? This option is causing a lot of problems to my server and weird bugs.
Do you mean that OFFLINE UUIDs type causes issues?

**Comment by PABLORAGNIzc** [comment]
I wanted to know what happens if I put OFFLINE in uniqueIdsType and having registered users, what could go wrong?

When I bought your plugin I forgot to put OFFLINE in that part of the configuration and in spigot you put that it is not recommended to put that once users have registered.

**Comment by Jakubson** [comment]
As I wrote in the wiki: https://github.com/Jakubson/JPremiumCleared/wiki#fixed-unique-ids
> When players are already registerd in your JPremium database and you change the `uniqueIdsType` option, players will not lose any data, but they will have UUID from the previous configuration. Only new players will have another UUID type.
