### ISSUE TITLE
Premium account login error

### ISSUE THREAD

**Issue by llt12213** [Jakubson/JPremiumCleared#26]
can't use Premium to login the server ,and console says "Error authenticating Dr_Li with minecraft.net" (Dr_Li is my account's ID)
how to fix it?
im using the latest version

**Comment by llt12213** [comment]
> 无法使用 Premium 登录服务器，控制台显示“使用 minecraft.net 验证 Dr_Li 时出错”（Dr_Li 是我的帐户 ID）
> 如何解决？
> 我使用的是最新版本

and if i use cracked account it will says null on the client

**Comment by Jakubson** [comment]
> Error authenticating Dr_Li with minecraft.net

If you are using the premium launcher, it is not caused by JPremium, but by authorization servers or launcher.



> > 无法使用 Premium 登录服务器，控制台显示“使用 minecraft.net 验证 Dr_Li 时出错”（Dr_Li 是我的帐户 ID）
> > 如何解决？
> > 我使用的是最新版本
> 
> and if i use cracked account it will says null on the client

Please read the wiki before reporting anything. You will find an answer there: https://github.com/Jakubson/JPremiumCleared/wiki#joining-issues
