### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by CarlosQuinto33333** [Jakubson/JPremiumCleared#28]
Español
I have a problem, several users are not allowed to enter with their original nickname, for example my user Calel gets an error that he enters as calel, without the initial capital letter

**Comment by Jakubson** [comment]
It means there are a user with `calel` nickname, so it is the reason why they cannot join. They need to change the nickname to `calel`  or you need to remove `calel` user from from your JPremium database. You can do it manually (your proxy must be disable when you are removing it) or use a command `/forcepurgeuserprofile`, but before execute this command, execute `/forceviewuserprofile` and make sure that the command returns the user you want to remove.
