### ISSUE TITLE
JPremium - Issue

### ISSUE THREAD

**Issue by kristian198** [Jakubson/JPremiumCleared#30]
Hi,

I have a problem with JPremium. I have servers on VPS and other services (MySQL, phpMyAdmin, etc...)

Link: https://pastebin.com/XgVz5BpS

**Comment by Jakubson** [comment]
Please do not report MySQL errors to me because it is always caused by a MySQL server or wrong configuration: https://github.com/Jakubson/JPremiumCleared/wiki#database-issues
