### ISSUE TITLE
Javadoc missing in API

### ISSUE THREAD

**Issue by misuda12** [Jakubson/JPremiumCleared#4]
Hello fellow developer,

I think its standard nowdays to implement javaDoc to API, especially if it is software for authenticating players.
Since your code is obfuscated, there is no way we can assume what each method is doing exactly, if we can provide nulls, when its returning null for User, when FailedException is thrown exactly or if it is even thread safe, since you are using async methods.

Can you please expose or generate javaDoc ? I will really appreciate it
- Martin (@WarfareMCNetwork)

**Comment by Jakubson** [comment]
Hi, Thanks your for an idea. I will try to describe all methods and generate javadoc soon.
