### ISSUE TITLE
Player loosing any maps in slot

### ISSUE THREAD

**Issue by misuda12** [Jakubson/JPremiumCleared#5]
Hello Jakubson,
Let's say cracked player is playing normally, he made up his own map, and when he place it in lets say slot 1, and disconnects, that map is gone.

Can you make check for map ID or something ?
m12

Images:
- before
![image](https://user-images.githubusercontent.com/19598684/107119461-fed24980-6887-11eb-956a-8e0387bdadda.png)
- after
![image](https://user-images.githubusercontent.com/19598684/107119475-13164680-6888-11eb-8454-de9309162649.png)

**Comment by Jakubson** [comment]
Hi, Thanks you for reporting it. I will check it and fix it.
